### ISSUE TITLE
Remove the topbar + title

### ISSUE THREAD

**Issue by mikejensen0** [andreasalstrup/CoShare#29]
![image](https://github.com/andreasalstrup/CoShare/assets/43805784/9e291243-6e2c-450d-987d-230c101c4cf5)
Each page has a top bar with a title. This is not needed and needs to get removed. I am unsure how to remove it. It is related to the following code found in `app\_layout.tsx`:
![image](https://github.com/andreasalstrup/CoShare/assets/43805784/e10e8527-0182-4d0f-ac16-7eb3fa6b47be)

**Comment by UnluckyBird** [comment]
Fixed in #31
